### ISSUE TITLE
Panic when rendering chart in wasm32 server (Cloudflare Workers)

### ISSUE THREAD

**Issue by avsaase** [feral-dot-io/leptos-chartistry#35] opened 2024-11-25 21:12 UTC
I'm building an SSR app running on Cloudflare Workers and I get a panic when rendering a simple chart. 

The panic I get is 
```
Error: called `Option::unwrap_throw()` on a `None` value (/home/alexander/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.6.11/src/lib.rs:1024:67)
```
It seems to wrong when something is trying to get the window [here](https://github.com/leptos-rs/leptos/blob/e29d31e686b75b62a6413e9b386dccba425b68f9/leptos_dom/src/lib.rs#L1024). This static is used by the `window` function just below but I haven't been able to find what is calling this function when the panic occurs. I see it's used a lot in leptos-use but I'm not sure if the error actually originates there so I wanted to open an issue here first.

**Comment by feral-dot-io** [comment] 2024-11-25 21:29
It'll probably be from `leptos-chartistry/src/use_watched_node.rs` which uses leptos-use.

I'm not familiar with CF's workers, is there anything specific about the environment that would trigger this problem? Can you reproduce the error locally? Are you able to provide me with something reproducible?

**Comment by avsaase** [comment] 2024-11-26 19:49
I manged to solve the problem by adding an explicit (optional) dependency for `leptos-use` 0.13 and enabling the `ssr` feature when the `ssr` feature of my project is enabled. I have not check if this is the case, but I suspect that `leptos-use` somewhere uses the target architecture to determine of if the code is compiled for the server or the client. Cloudflare Workers written in Rust are compiled with the `wasm32-unknown-unknown` target so this server/client detection probably fails. 

Interestingly the problem is not solved by enabling `leptos-use`'s `wasm_ssr` feature.

**Comment by feral-dot-io** [comment] 2024-12-05 11:16
Thanks for the follow-up. Unless I'm mistaken, this looks like a problem in leptos-use so I'll close this issue. Let me know if that's not the case.

I think this would be worthwhile following up with leptos-use but might already be fixed: https://github.com/Synphonyte/leptos-use/issues/204

**Closed** 2024-12-05 11:16 UTC
